### ISSUE TITLE
Error on Display Owner

### ISSUE THREAD

**Issue by DanBonehill** [DanBonehill/SFG-pet-clinic#59]
2019-03-11 08:50:38.367 ERROR 4776 --- [nio-8080-exec-1] o.a.c.c.C.[.[.[/].[dispatcherServlet]    : Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed; nested exception is org.thymeleaf.exceptions.TemplateInputException: An error happened during template parsing (template: "class path resource [templates/owners/ownerDetails.html]")] with root cause

org.springframework.expression.spel.SpelEvaluationException: EL1008E: Property or field 'type' cannot be found on object of type 'com.danbonehill.sfgpetclinic.model.Pet' - maybe not public or not valid?
	at org.springframework.expression.spel.ast.PropertyOrFieldReference.readProperty(PropertyOrFieldReference.java:217) ~[spring-expression-5.1.5.RELEASE.jar:5.1.5.RELEASE]
	at org.springframework.expression.spel.ast.PropertyOrFieldReference.getValueInternal(PropertyOrFieldReference.java:104) ~[spring-expression-5.1.5.RELEASE.jar:5.1.5.RELEASE]
	at org.springframework.expression.spel.ast.PropertyOrFieldReference.access$000(PropertyOrFieldReference.java:51) ~[spring-expression-5.1.5.RELEASE.jar:5.1.5.RELEASE]

**Comment by DanBonehill** [comment]
Relates to #52
